/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as AlertFeedRouteImport } from './routes/alert-feed'
import { Route as IndexRouteImport } from './routes/index'

const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertFeedRoute = AlertFeedRouteImport.update({
  id: '/alert-feed',
  path: '/alert-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alert-feed': typeof AlertFeedRoute
  '/positions': typeof PositionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alert-feed': typeof AlertFeedRoute
  '/positions': typeof PositionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alert-feed': typeof AlertFeedRoute
  '/positions': typeof PositionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alert-feed' | '/positions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alert-feed' | '/positions'
  id: '__root__' | '/' | '/alert-feed' | '/positions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertFeedRoute: typeof AlertFeedRoute
  PositionsRoute: typeof PositionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert-feed': {
      id: '/alert-feed'
      path: '/alert-feed'
      fullPath: '/alert-feed'
      preLoaderRoute: typeof AlertFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertFeedRoute: AlertFeedRoute,
  PositionsRoute: PositionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
